// Code generated by flutter_gopher. DO NOT EDIT.
package bridge

var InitMethodHandle func(handle func(method int, data []byte) ([]byte, error))

var CallGoMethod func(method int, data []byte) ([]byte, error)

var CallDartMethod func(method int, data []byte)
