// Code generated by flutter_gopher. DO NOT EDIT.
#include "../include/bridge.h"

#ifndef FG_BRIDGE_NAPI_H
#define FG_BRIDGE_NAPI_H

#ifdef __cplusplus
extern "C" {
#endif

FgResponse fg_call_platform_method(FgRequest request);
FgResponse fg_call_platform_method_safe(FgRequest request);

#ifdef __cplusplus
}
#endif

#endif
