//go:build openharmony

// Code generated by flutter_gopher. DO NOT EDIT.
package openharmony

/*
#cgo LDFLAGS: -lace_napi.z -lhilog_ndk.z -static-libstdc++

#include "bridge_napi.h"
*/
import "C"
import (
	"unsafe"

	utils "{{.ProjectName}}/bridge/utils"

	godartapi "github.com/czg99/go-dart-api"
)

//export fg_call_platform_method_{{.ID}}
func fg_call_platform_method_{{.ID}}(request C.FgRequest) C.FgResponse {
	return C.fg_call_platform_method_safe(request)
}

//export fg_call_platform_method_async_{{.ID}}
func fg_call_platform_method_async_{{.ID}}(port C.int64_t, request C.FgRequest) {
	go func() {
		response := C.fg_call_platform_method_safe(request)
		ptr := utils.CValueToPtr(response)
		if suc := godartapi.SendToDartPort(int64(port), unsafe.Pointer(ptr)); !suc {
			C.free_fgresponse(ptr)
			C.free(unsafe.Pointer(ptr))
		}
	}()
}
