// Code generated by flutter_gopher. DO NOT EDIT.
package bridge

import "log"

type MethodHandle func(method string, data []byte) []byte

var goMethodHandle MethodHandle = nil

func callGoMethod(method string, data []byte) []byte {
	if goMethodHandle == nil {
		log.Println("go method handle not init")
		return nil
	}
	return goMethodHandle(method, data)
}
