// Code generated by flutter_gopher. DO NOT EDIT.
package bridge

import (
	"fmt"
)

type MethodHandle func(method string, data []byte) ([]byte, error)

var goMethodHandle MethodHandle = nil

func callGoMethod(method string, data []byte) (result []byte, err error) {
	if goMethodHandle == nil {
		return nil, fmt.Errorf("call go method: %s, error: go method handle not init", method)
	}
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("call go method: %s, panic err: %v", method, r)
		}
	}()

	result, err = goMethodHandle(method, data)
	if err != nil {
		return nil, fmt.Errorf("call go method: %s, error: %w", method, err)
	}
	return
}
