// Code generated by flutter_gopher. DO NOT EDIT.
package bridge

var InitMethodHandle func(handle func(method string, data []byte) []byte)

var CallGoMethod func(method string, data []byte) []byte

var CallDartMethod func(method string, data []byte)
