// Code generated by flutter_gopher. DO NOT EDIT.
package {{.PackageName}}

import java.nio.charset.StandardCharsets
import androidx.annotation.Keep

interface FgBridgeDelegate {
    fun methodHandle(method: Int, data: ByteArray?): Result<ByteArray?>
}

@Keep
class FgJniResponse(
    @JvmField @Keep val data: ByteArray?,
    @JvmField @Keep val error: ByteArray?
)

abstract class FgBridge {
    companion object {
        init {
            System.loadLibrary("{{.LibName}}")
            nativeInit()
        }
        
        @JvmStatic
        var delegate: FgBridgeDelegate? = null

        @JvmStatic private external fun nativeInit()
        @JvmStatic private external fun nativeCallGoMethod(method: Int, data: ByteArray?): FgJniResponse
        @JvmStatic private external fun nativeCallDartMethod(method: Int, data: ByteArray?)

        @JvmStatic
        fun callGoMethod(method: Int, data: ByteArray? = null): Result<ByteArray?> {
            val resp = nativeCallGoMethod(method, data)
            return if (resp.error != null) {
                Result.failure(Exception(String(resp.error, StandardCharsets.UTF_8)))
            } else {
                Result.success(resp.data)
            }
        }

        @JvmStatic
        fun callDartMethod(method: Int, data: ByteArray? = null) {
            nativeCallDartMethod(method, data)
        }

        @JvmStatic
        @Keep
        private fun onNativeHandle(method: Int, data: ByteArray?): FgJniResponse {
            val d = delegate ?: return FgJniResponse(null, "init err: delegate is null".toByteArray())
            return try {
                val result = d.methodHandle(method, data)
                if (result.isSuccess) {
                    FgJniResponse(result.getOrNull(), null)
                } else {
                    val msg = result.exceptionOrNull()?.message ?: "unknown error"
                    FgJniResponse(null, msg.toByteArray())
                }
            } catch (e: Throwable) {
                FgJniResponse(null, "caught err: ${e.message}".toByteArray())
            }
        }
    }
}