// Code generated by flutter_gopher. DO NOT EDIT.
package bridge

/*
#include "include/bridge.h"
*/
import "C"
import (
	"errors"
	"sync"
	"unsafe"

	utils "{{.ProjectName}}/bridge/utils"

	godartapi "github.com/czg99/go-dart-api"
)

func callPlatformMethod(method int32, data []byte) ([]byte, error) {
	request := mapToFgRequest(method, data)
	response := C.fg_call_platform_method_{{.ID}}(request)
	return mapFromFgResponse(response)
}

func callDartMethod(method int32, data []byte) {
	if len(global_port) == 0 {
		return
	}
	request := mapToFgRequest(method, data)
	fg_call_dart_method_{{.ID}}(request)
}

var global_port = make(map[int64]struct{})
var global_lock = sync.Mutex{}

//export fg_init_dart_api_{{.ID}}
func fg_init_dart_api_{{.ID}}(api unsafe.Pointer, port C.int64_t) {
	godartapi.InitDartApi(api)
	global_lock.Lock()
	defer global_lock.Unlock()
	global_port[int64(port)] = struct{}{}
}

//export fg_call_dart_method_{{.ID}}
func fg_call_dart_method_{{.ID}}(request C.FgRequest) {
	if len(global_port) == 0 {
		freeFgRequest(&request, true)
		return
	}
	global_lock.Lock()
	defer global_lock.Unlock()
	count := len(global_port)
	for port, _ := range global_port {
		value := request
		if (count > 1) {
			value = C.FgRequest {
				method: request.method,
				data: copyFgData(request.data),
			}
		}
		ptr := utils.CValueToPtr(value)
		if suc := godartapi.SendToDartPort(port, unsafe.Pointer(ptr)); !suc {
			freeFgRequest(ptr, false)
			delete(global_port, port)
		}
		count--
	}
}

//export fg_call_go_method_{{.ID}}
func fg_call_go_method_{{.ID}}(request C.FgRequest) C.FgResponse {
	method, data := mapFromFgRequest(request)
	result, err := callGoMethod(method, data)
	return mapToFgResponse(result, err)
}

//export fg_call_go_method_async_{{.ID}}
func fg_call_go_method_async_{{.ID}}(port C.int64_t, request C.FgRequest) {
	go func() {
		response := fg_call_go_method_{{.ID}}(request)
		ptr := utils.CValueToPtr(response)
		if suc := godartapi.SendToDartPort(int64(port), unsafe.Pointer(ptr)); !suc {
			freeFgResponse(ptr, false)
		}
	}()
}

var fgPlatformMethodHandle C.FgPlatformMethodHandle = nil

//export fg_init_platform_method_handle_{{.ID}}
func fg_init_platform_method_handle_{{.ID}}(handle C.FgPlatformMethodHandle) {
	fgPlatformMethodHandle = handle
}

func mapFromFgRequest(from C.FgRequest) (int32, []byte) {
	method := int32(from.method)
	data := mapToBytes(from.data)
	return method, data
}

func mapToFgRequest(method int32, data []byte) C.FgRequest {
	return C.FgRequest{
		method: C.int32_t(method),
		data:   mapFromBytes(data),
	}
}

func mapFromFgResponse(from C.FgResponse) ([]byte, error) {
	data := mapToBytes(from.data)
	err := mapToError(from.error)
	return data, err
}

func mapToFgResponse(data []byte, err error) C.FgResponse {
	response := C.FgResponse{
		data: mapFromBytes(data),
	}
	if err != nil {
		response.error = mapFromError(err)
	}
	return response
}

func mapFromString(from string) C.FgData {
	return mapFromBytes([]byte(from))
}

func mapToString(from C.FgData) string {
	if from.data == nil {
		return ""
	}
	return string(mapToBytes(from))
}

func mapFromError(from error) C.FgData {
	if from == nil {
		return C.FgData{}
	}
	return mapFromString(from.Error())
}

func mapToError(from C.FgData) error {
	if from.data == nil {
		return nil
	}
	return errors.New(mapToString(from))
}

func mapFromBytes(from []byte) C.FgData {
	if len(from) == 0 {
		return C.FgData{}
	}
	data := C.CBytes(from)
	size := C.int32_t(len(from))
	return C.FgData{
		data: data,
		size: size,
	}
}

func mapToBytes(from C.FgData) []byte {
	if from.data == nil {
		return nil
	}
	defer C.free(from.data)
	return C.GoBytes(unsafe.Pointer(from.data), C.int32_t(from.size))
}

func freeFgRequest(value *C.FgRequest, freeInnerOnly bool) {
	C.free(value.data.data)
	if !freeInnerOnly {
		C.free(unsafe.Pointer(value))
	}
}

func freeFgResponse(value *C.FgResponse, freeInnerOnly bool) {
	C.free(value.data.data)
	C.free(value.error.data)
	if !freeInnerOnly {
		C.free(unsafe.Pointer(value))
	}
}

func copyFgData(src C.FgData) C.FgData {
	if src.data == nil || src.size <= 0 {
		return C.FgData{}
	}

	dstData := C.malloc(C.size_t(src.size))
	C.memcpy(dstData, src.data, C.size_t(src.size))
	return C.FgData{
		data: dstData,
		size: src.size,
	}
}
