// Code generated by flutter_gopher. DO NOT EDIT.
package bridge

import (
	"errors"
	"fmt"
)

type MethodHandle func(method int, data []byte) ([]byte, error)

var goMethodHandle MethodHandle = nil

func callGoMethod(method int, data []byte) (result []byte, err error) {
	if goMethodHandle == nil {
		return nil, errors.New("init err: go method handle not init")
	}
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic err: %v", r)
		}
	}()

	result, err = goMethodHandle(method, data)
	if err != nil {
		return nil, err
	}
	return
}
