//go:build !openharmony

// Code generated by flutter_gopher. DO NOT EDIT.
package bridge

/*
#include "include/bridge.h"
*/
import "C"
import (
	"unsafe"

	godartapi "github.com/czg99/go-dart-api"
)

//export fg_call_platform_method_{{.ID}}
func fg_call_platform_method_{{.ID}}(request C.FgRequest) C.FgResponse {
	response := C.FgResponse{}
	if fgPlatformMethodHandle == nil {
		freeFgRequest(&request, true)
		return response
	}

	C.call_fg_platform_method_handle(fgPlatformMethodHandle, request, &response)
	return response
}

//export fg_call_platform_method_async_{{.ID}}
func fg_call_platform_method_async_{{.ID}}(port C.int64_t, request C.FgRequest) {
	go func() {
		response := fg_call_platform_method_{{.ID}}(request)
		ptr := cValueToPtr(response)
		if suc := godartapi.SendToDartPort(int64(port), unsafe.Pointer(ptr)); !suc {
			freeFgResponse(ptr, false)
		}
	}()
}
