//go:build openharmory

// Code generated by flutter_gopher. DO NOT EDIT.
package bridge

/*
#cgo LDFLAGS: -lace_napi.z

#include "cpp/napi_init.cpp"
*/
import "C"
import (
	"unsafe"

	godartapi "github.com/czg99/go-dart-api"
)

//export fg_call_platform_method_{{.ID}}
func fg_call_platform_method_{{.ID}}(request C.FgRequest) C.FgResponse {
	return C.fg_call_platform_method_safe(request)
}

//export fg_call_platform_method_async_{{.ID}}
func fg_call_platform_method_async_{{.ID}}(port C.int64_t, request C.FgRequest) {
	go func() {
		response := C.fg_call_platform_method_safe(request)
		ptr := cValueToPtr(response)
		if suc := godartapi.SendToDartPort(int64(port), unsafe.Pointer(ptr)); !suc {
			freeFgResponse(ptr, false)
		}
	}()
}
