// Code generated by flutter_gopher. DO NOT EDIT.
package bridge

func InitMethodHandle(handle MethodHandle) {
	goMethodHandle = handle
}

func CallDartMethod(method int, data []byte) {
	callDartMethod(method, data)
}

func CallPlatformMethod(method int, data []byte) ([]byte, error) {
	return callPlatformMethod(method, data)
}
