// Code generated by flutter_gopher. DO NOT EDIT.
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

#ifndef FG_BRIDGE_H
#define FG_BRIDGE_H

typedef struct {
	void* data;
	int32_t size;
} FgData;

typedef struct {
	int32_t method;
	FgData data;
} FgRequest;

typedef struct {
	FgData data;
	FgData error;
} FgResponse;

typedef void (*FgPlatformMethodHandle)(FgRequest, FgResponse*);

#ifdef _WIN32
    #define DLLEXPORT __declspec(dllexport)
#else
    #define DLLEXPORT __attribute__((visibility("default")))
#endif

extern DLLEXPORT void fg_init_dart_api_{{.ID}}(void* api, int64_t port);
extern DLLEXPORT void fg_call_dart_method_{{.ID}}(FgRequest request);

extern DLLEXPORT FgResponse fg_call_go_method_{{.ID}}(FgRequest request);
extern DLLEXPORT void fg_call_go_method_async_{{.ID}}(int64_t port, FgRequest request);

extern DLLEXPORT void fg_init_platform_method_handle_{{.ID}}(FgPlatformMethodHandle handle);
extern DLLEXPORT FgResponse fg_call_platform_method_{{.ID}}(FgRequest request);
extern DLLEXPORT void fg_call_platform_method_async_{{.ID}}(int64_t port, FgRequest request);

static inline void call_fg_platform_method_handle(FgPlatformMethodHandle handle, FgRequest request, FgResponse* response) {
	handle(request, response);
}

static void free_fgdata(FgData* data) {
    if (data->data != NULL) {
        free(data->data);
        data->data = NULL;
    }
    data->size = 0;
}

static void free_fgrequest(FgRequest* request) {
	request->method = 0;
    free_fgdata(&request->data);
}

static void free_fgresponse(FgResponse* response) {
    free_fgdata(&response->data);
    free_fgdata(&response->error);
}

static inline void fg_bridge_binding_{{.ID}}(void) {
    uintptr_t ptr = 0;
	ptr ^= (uintptr_t)fg_init_dart_api_{{.ID}};
	ptr ^= (uintptr_t)fg_call_dart_method_{{.ID}};
	ptr ^= (uintptr_t)fg_call_go_method_{{.ID}};
	ptr ^= (uintptr_t)fg_call_go_method_async_{{.ID}};
	ptr ^= (uintptr_t)fg_call_platform_method_{{.ID}};
	ptr ^= (uintptr_t)fg_call_platform_method_async_{{.ID}};
}

#endif
