// Code generated by flutter_gopher. DO NOT EDIT.
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

#ifndef FG_BRIDGE_H
#define FG_BRIDGE_H

typedef struct {
	void* data;
	int size;
} FgData;

typedef struct {
	int method;
	FgData data;
} FgRequest;

typedef struct {
	FgData data;
	FgData error;
} FgResponse;


typedef void (*FgPlatformMethodHandle)(FgRequest, FgResponse*);
static inline void call_fg_platform_method_handle(FgPlatformMethodHandle handle, FgRequest request, FgResponse* response) {
	handle(request, response);
}

#ifdef _WIN32
    #define DLLEXPORT __declspec(dllexport)
#else
    #define DLLEXPORT __attribute__((visibility("default")))
#endif

extern DLLEXPORT void fg_init_dart_api_{{.Timestamp}}(void* api, int64_t port);
extern DLLEXPORT void fg_init_platform_method_handle_{{.Timestamp}}(FgPlatformMethodHandle handle);

extern DLLEXPORT void fg_call_dart_method_{{.Timestamp}}(FgRequest request);
extern DLLEXPORT FgResponse fg_call_go_method_{{.Timestamp}}(FgRequest request);
extern DLLEXPORT void fg_call_go_method_async_{{.Timestamp}}(int64_t port, FgRequest request);
extern DLLEXPORT FgResponse fg_call_platform_method_{{.Timestamp}}(FgRequest request);
extern DLLEXPORT void fg_call_platform_method_async_{{.Timestamp}}(int64_t port, FgRequest request);

#endif