// The Android Gradle Plugin builds the native code with the Android NDK.

group = "{{.PackageName}}"
version = "1.0"

buildscript {
    ext.kotlin_version = "1.8.22"
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath("com.android.tools.build:gradle:8.1.0")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version")
        classpath("com.google.protobuf:protobuf-gradle-plugin:0.9.5")
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: "com.android.library"
apply plugin: "kotlin-android"
apply plugin: 'com.google.protobuf'

android {
    if (project.android.hasProperty("namespace")) {
        namespace = "{{.PackageName}}"
    }

    compileSdk = project.hasProperty('flutter') ? flutter.compileSdkVersion : 35
    ndkVersion = project.hasProperty('flutter') ? flutter.ndkVersion : android.ndkVersion

    defaultConfig {
        minSdk = project.hasProperty('flutter') ? flutter.minSdkVersion : 21
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }
    
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
            proto.srcDirs = ['../protos/proto']
        }
    }
    
    dependencies {
        implementation 'net.java.dev.jna:jna:5.17.0@aar'
        implementation 'com.google.protobuf:protobuf-javalite:3.25.8'
    }
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.25.8'
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                remove java
            }
            task.plugins {
                java {
                    option 'lite'
                }
            }
        }
    }
}
