// Code generated by flutter_gopher. DO NOT EDIT.
#import <Foundation/Foundation.h>

@protocol FgBridgeDelegate <NSObject>
- (NSData*)methodHandle:(NSString*)method data:(NSData*)data error:(NSError**)error;
@end


@interface FgBridge : NSObject

@property (nonatomic, weak) id<FgBridgeDelegate> delegate;

+ (instancetype)sharedInstance;

- (NSData*)callGoMethod:(NSString*)method data:(NSData*)data error:(NSError**)error;
- (void)callDartMethod:(NSString*)method data:(NSData*)data;

@end
