// Code generated by flutter_gopher. DO NOT EDIT.
#import "FgBridge.h"

#include "../../gosrc/bridge/include/bridge.h"

extern void fg_bridge_binding_{{.Timestamp}}(void);
extern void fg_ffi_binding_{{.Timestamp}}(void);

@implementation FgBridge

typedef NSString FgError;

__weak id<FgBridgeDelegate> globalDelegate = nil;

void methodHandle(FgRequest request, FgResponse* response) {
    [FgBridge methodHandle:request response:response];
}

+ (void)initialize {
    fg_bridge_binding_{{.Timestamp}}();
    fg_ffi_binding_{{.Timestamp}}();
    fg_init_platform_method_handle_{{.Timestamp}}(methodHandle);
}

+ (void)setDelegate:(id<FgBridgeDelegate>)delegate {
    globalDelegate = delegate;
}

+ (FgData)mapFgDataFromNSData:(NSData*)from {
    FgData result = {};
    if (from != nil) {
        NSUInteger dataLen = [from length];
        void* data = malloc(dataLen);
        [from getBytes:data length:dataLen];
        result.data = data;
        result.size = (int)dataLen;
    }
    return result;
}

+ (NSData*)mapFgDataToNSData:(FgData)from {
    if (from.data == nil) return nil;
    NSData* result = [[NSData alloc] initWithBytes:from.data length:from.size];
    [self freeFgData:&from];
    return result;
}

+ (FgData)mapFgDataFromNSString:(NSString*)from {
    NSData* data = from != nil ? [from dataUsingEncoding:NSUTF8StringEncoding] : nil;
    return [self mapFgDataFromNSData:data];
}

+ (NSString*)mapFgDataToNSString:(FgData)from {
    if (from.data == nil) return @"";
    NSString* result = [[NSString alloc] initWithBytes:from.data length:from.size encoding:NSUTF8StringEncoding];
    [self freeFgData:&from];
    return result;
}

+ (FgData)mapFgDataFromFgError:(FgError*)from {
    return [self mapFgDataFromNSString:from];
}

+ (FgError*)mapFgDataToFgError:(FgData)from {
    if (from.data == nil) return nil;
    return [self mapFgDataToNSString:from];
}

+ (void)freeFgData:(FgData*)value {
    if (value->data != nil) {
        free(value->data);
        value->data = nil;
        value->size = 0;
    }
}

+ (void)methodHandle:(FgRequest)request response:(FgResponse*)response {
    int method = request.method;
    NSData* data = [self mapFgDataToNSData:request.data];

    if (globalDelegate == nil) {
        response->error = [self mapFgDataFromFgError:@"init err: delegate is nil"];
        return;
    }
    
    NSData* result = nil;
    NSError* error = nil;
    @try {
        result = [globalDelegate methodHandle:method data:data error:&error];
    } @catch (NSException *e) {
        NSString *caughtErr = [NSString stringWithFormat:@"caught err: %@", [e reason]];
        response->error = [self mapFgDataFromFgError:caughtErr];
    }
    
    if (error != nil) {
        response->error = [self mapFgDataFromFgError:error.localizedDescription];
        return;
    }
    response->data = [self mapFgDataFromNSData:result];
}

+ (NSData*)callGoMethod:(int)method data:(NSData*)data error:(NSError**)error {    
    FgRequest request = {
        .method = method,
        .data = [self mapFgDataFromNSData:data],
    };
    
    FgResponse response = fg_call_go_method_{{.Timestamp}}(request);
    
    NSData* result = [self mapFgDataToNSData:response.data];
    FgError* err = [self mapFgDataToFgError:response.error];
    if (err != nil) {
        *error = [NSError errorWithDomain:@"{{.PackageName}}" code:1 userInfo:@{NSLocalizedDescriptionKey: err}];
        return nil;
    }
    return result;
}

+ (void)callDartMethod:(int)method data:(NSData*)data {    
    FgRequest request = {
        .method = method,
        .data = [self mapFgDataFromNSData:data],
    };
    
    fg_call_dart_method_{{.Timestamp}}(request);
}

@end
