// Code generated by flutter_gopher. DO NOT EDIT.
#import <Foundation/Foundation.h>

@protocol FgBridgeDelegate <NSObject>
- (NSData*)methodHandle:(int32_t)method data:(NSData*)data error:(NSError**)error;
@end


@interface FgBridge : NSObject

+ (void)setDelegate:(id<FgBridgeDelegate>)delegate;

+ (NSData*)callGoMethod:(int32_t)method data:(NSData*)data error:(NSError**)error;
+ (void)callDartMethod:(int32_t)method data:(NSData*)data;

@end
