// Code generated by flutter_gopher. DO NOT EDIT.
#import "FgBridge.h"

#include "../../src/bridge/include/bridge.h"

@implementation FgBridge

typedef NSString FgError;

void methodHandle(FgRequest request, FgResponse* response) {
    [[FgBridge sharedInstance] methodHandle:request response:response];
}

+ (instancetype)sharedInstance {
    static FgBridge *sharedInstance = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        sharedInstance = [[self alloc] init];
        fg_enforce_binding_{{.Timestamp}}();
        fg_init_platform_method_handle_{{.Timestamp}}(methodHandle);
    });
    return sharedInstance;
}

- (FgData)mapFgDataFromNSData:(NSData*)from {
    FgData result = {};
    if (from != nil) {
        NSUInteger dataLen = [from length];
        void* data = malloc(dataLen);
        [from getBytes:data length:dataLen];
        result.data = data;
        result.size = (int)dataLen;
    }
    return result;
}

- (NSData*)mapFgDataToNSData:(FgData)from {
    if (from.data == nil) return nil;
    NSData* result = [[NSData alloc] initWithBytes:from.data length:from.size];
    [self freeFgData:&from];
    return result;
}

- (FgData)mapFgDataFromNSString:(NSString*)from {
    NSData* data = from != nil ? [from dataUsingEncoding:NSUTF8StringEncoding] : nil;
    return [self mapFgDataFromNSData:data];
}

- (NSString*)mapFgDataToNSString:(FgData)from {
    if (from.data == nil) return @"";
    NSString* result = [[NSString alloc] initWithBytes:from.data length:from.size encoding:NSUTF8StringEncoding];
    [self freeFgData:&from];
    return result;
}

- (FgData)mapFgDataFromFgError:(FgError*)from {
    return [self mapFgDataFromNSString:from];
}

- (FgError*)mapFgDataToFgError:(FgData)from {
    if (from.data == nil) return nil;
    return [self mapFgDataToNSString:from];
}

- (void)freeFgData:(FgData*)value {
    if (value->data != nil) {
        free(value->data);
        value->data = nil;
        value->size = 0;
    }
}

- (void)methodHandle:(FgRequest)request response:(FgResponse*)response {
    NSString* method = [self mapFgDataToNSString:request.method];
    NSData* data = [self mapFgDataToNSData:request.data];

    if (self.delegate == nil) {
        response->error = [self mapFgDataFromFgError:@"init err: delegate is nil"];
        return;
    }
    
    NSData* result = nil;
    NSError* error = nil;
    @try {
        result = [self.delegate methodHandle:method data:data error:&error];
    } @catch (NSException *e) {
        NSString *caughtErr = [NSString stringWithFormat:@"caught err: %@", [e reason]];
        response->error = [self mapFgDataFromFgError:caughtErr];
    }
    
    if (error != nil) {
        response->error = [self mapFgDataFromFgError:error.localizedDescription];
        return;
    }
    response->data = [self mapFgDataFromNSData:result];
}

- (NSData*)callGoMethod:(NSString*)method data:(NSData*)data error:(NSError**)error {
    if (method == nil) {
        return nil;
    }
    
    FgRequest request = {
        .method = [self mapFgDataFromNSString:method],
        .data = [self mapFgDataFromNSData:data],
    };
    
    FgResponse response = fg_call_go_method_{{.Timestamp}}(request);
    
    NSData* result = [self mapFgDataToNSData:response.data];
    FgError* err = [self mapFgDataToFgError:response.error];
    if (err != nil) {
        *error = [NSError errorWithDomain:@"{{.PackageName}}" code:1 userInfo:@{NSLocalizedDescriptionKey: err}];
        return nil;
    }
    return result;
}

- (void)callDartMethod:(NSString*)method data:(NSData*)data {
    if (method == nil) {
        return;
    }
    
    FgRequest request = {
        .method = [self mapFgDataFromNSString:method],
        .data = [self mapFgDataFromNSData:data],
    };
    
    fg_call_go_method_{{.Timestamp}}(request);
}

@end
